### ISSUE TITLE
スラコマで・・・

### ISSUE THREAD

**Issue by sisiruirui-sisi** [sisiruirui-sisi/rowen_issues#11]
**どのような機能がほしいか**

- [x] メイン取得コマンドをスラッシュコマンドにする
- [x] topコマンドをスラッシュコマンドにする
- [x] 他修正

**その他**

なし

**Comment by sikkokuhyouma** [comment]
リアルご飯来たので離席(をい
じゃなくて、ちゃんとしたスラッシュコマンドの名前にします。

**Comment by sikkokuhyouma** [comment]
修正中

**Comment by sikkokuhyouma** [comment]
修正完了につきクローズ。
